name: AWS Resource Deletion

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Select the resource to delete'
        required: true
        type: choice
        options:
          - delete_deployment_group
          - delete_application
          - unsubscribe_sns
          - delete_cloudwatch_alarm
          - delete_sns_topic
          - delete_lambda
      aws_region:
        description: 'AWS Region'
        required: true
        type: choice
        options:
          - eu-west-1
          - eu-west-2
      resource_identifier:
        description: 'Resource Identifier (see description below for what to enter based on your selected command)'
        required: true
        type: string
      secondary_identifier:
        description: 'Secondary Identifier (only required for delete_deployment_group - enter deployment group name)'
        required: false
        type: string

jobs:
  delete-resource:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.aws_region }}
        
    - name: Validate inputs
      run: |
        case "${{ github.event.inputs.command }}" in
          "delete_deployment_group")
            if [ -z "${{ github.event.inputs.resource_identifier }}" ] || [ -z "${{ github.event.inputs.secondary_identifier }}" ]; then
              echo "Error: Both application name and deployment group name are required for delete_deployment_group"
              exit 1
            fi
            ;;
          *)
            if [ -z "${{ github.event.inputs.resource_identifier }}" ]; then
              echo "Error: Resource identifier is required"
              exit 1
            fi
            ;;
        esac
        
    - name: Execute deletion script
      run: |
        CMD="python deletion_script.py ${{ github.event.inputs.command }}"
        case "${{ github.event.inputs.command }}" in
          "delete_deployment_group")
            CMD="$CMD ${{ github.event.inputs.resource_identifier }} ${{ github.event.inputs.secondary_identifier }}"
            ;;
          *)
            CMD="$CMD ${{ github.event.inputs.resource_identifier }}"
            ;;
        esac
        echo "Executing: $CMD"
        $CMD 